[package]
name = "dnsseedrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32ct = { version = "0.2.0", features = ["alloc"] }
bitcoin = "0.31.1"
clap = { version = "4.5.1", features = ["derive"] }
crossbeam = "0.8.4"
rusqlite = "0.31.0"
sha3 = "0.10.8"
threadpool = "1.8.1"

[patch.crates-io]
bitcoin = { git = "https://github.com/achow101/rust-bitcoin", branch = "fix-cjdns-decode-0.31" }
